### ISSUE TITLE
ArgumentError: value must be a number

### ISSUE THREAD

**Issue by velterity** [axsuul/plex-media-server-exporter#10]
Hey, was trying this out and I see the following error in the ui:

Puma caught this error: value must be a number (ArgumentError)
/usr/local/bundle/gems/prometheus-client-4.0.0/lib/prometheus/client/gauge.rb:17:in `set'
/srv/lib/middleware/collector.rb:216:in `block in set_gauge_metric_values_or_reset_missing'
/srv/lib/middleware/collector.rb:215:in `each'
/srv/lib/middleware/collector.rb:215:in `set_gauge_metric_values_or_reset_missing'
/srv/lib/middleware/collector.rb:75:in `ensure in call'
/srv/lib/middleware/collector.rb:75:in `call'
/usr/local/bundle/gems/rack-3.0.1/lib/rack/deflater.rb:47:in `call'
/usr/local/bundle/gems/puma-6.0.0/lib/puma/configuration.rb:268:in `call'
/usr/local/bundle/gems/puma-6.0.0/lib/puma/request.rb:89:in `block in handle_request'
/usr/local/bundle/gems/puma-6.0.0/lib/puma/thread_pool.rb:343:in `with_force_shutdown'
/usr/local/bundle/gems/puma-6.0.0/lib/puma/request.rb:88:in `handle_request'
/usr/local/bundle/gems/puma-6.0.0/lib/puma/server.rb:430:in `process_client'
/usr/local/bundle/gems/puma-6.0.0/lib/puma/server.rb:233:in `block in run'
/usr/local/bundle/gems/puma-6.0.0/lib/puma/thread_pool.rb:150:in `block in spawn_thread'

The docker logs show the following:

2023-07-12 18:46:14 +0000 Rack app ("GET /" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:46:14 +0000 Rack app ("GET /favicon.ico" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:46:14 +0000 Rack app ("GET /" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:46:14 +0000 Rack app ("GET /favicon.ico" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:46:15 +0000 Rack app ("GET /" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:46:15 +0000 Rack app ("GET /favicon.ico" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:47:24 +0000 Rack app ("GET /metrics" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:47:24 +0000 Rack app ("GET /favicon.ico" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:47:26 +0000 Rack app ("GET /metrics" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:47:26 +0000 Rack app ("GET /favicon.ico" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:47:27 +0000 Rack app ("GET /metrics" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:47:27 +0000 Rack app ("GET /favicon.ico" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:48:50 +0000 Rack app ("GET /metrics" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:48:50 +0000 Rack app ("GET /favicon.ico" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:52:06 +0000 Rack app ("GET /metrics" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:52:06 +0000 Rack app ("GET /favicon.ico" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:52:07 +0000 Rack app ("GET /metrics" - (192.168.1.163)): #<ArgumentError: value must be a number>
2023-07-12 18:52:07 +0000 Rack app ("GET /favicon.ico" - (192.168.1.163)): #<ArgumentError: value must be a number>

**Comment by axsuul** [comment]
Can I please see your `docker-compose.yml` or whatever input you're using to run the Docker iamge?

**Comment by velterity** [comment]
I tried a few different options for PLEX_ADDR, thinking it was that, but still wasn't working.

Here's my env file:

CADDY_PROXY=caddy_proxy
PLEX_ADDR=http://192.168.1.251:32400
PLEX_TOKEN=******


Compose file:


```
---
version: "3.7"

networks:
  default:
    name: ${CADDY_PROXY}
    external: true 

services:

  plex-exporter:
    container_name: plex-media-server-exporter
    image: ghcr.io/axsuul/plex-media-server-exporter
    hostname: plex-exporter
    restart: unless-stopped
    ports:
      - 9594:9594
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    volumes:
      - plex_exporter_data:/app/config
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  plex_exporter_data:
    name: plex_exporter_data
```
